In [1]:
import numpy as np
import random as rd
from copy import deepcopy
HUMAN = -1
PC = 1
fichas = {HUMAN: "o" , PC: "x"}

In [2]:
class Estado(object):
    
    def __init__(self, tablero = [[0,  0, 0], [0,  0, 0], [0,  0, 0]]):
        self.tablero = tablero
    
    def __str__(self):
        str_tablero = ""
        for i in range(3):
            for j in range(3):
                casilla = fichas[self.tablero[i][j]] if self.tablero[i][j] !=0 else  " "
                str_tablero += casilla
                if j<2:
                    str_tablero += "│"

            str_tablero += "\n"
            if i<2:
                str_tablero += "─┼─┼─\n" 

        return str_tablero + "\n"

In [3]:
#prueba de impresion
est = Estado()
tab = [[0,0,1],[0,1,0],[0,0,0]]
est.tablero=tab
print(est)

 │ │x
─┼─┼─
 │x│ 
─┼─┼─
 │ │ 




In [4]:
#comprobar si es estado final
def isendutil(esta):
    table=esta.tablero
    #comprobar filas
    for i in range(len(table)):
        cont=0
        for j in range(len(table)):
            if table[i][0]==table[i][j] and table[i][0] != 0:
                cont+=1
        if cont==3:
            return True, -1 if table[0][i] == -1 else 1
    #comprobar columnas
    for i in range(len(table)):
        cont=0
        for j in range(len(table)):
            if table[0][i]==table[j][i] and table[0][i] != 0:
                cont+=1
        if cont==3:
            return True, -1 if table[0][i] == -1 else 1
    
    cont=0
    #comprobar diagonal derecha izquierda
    for i in range(len(table)):
        if table[0][0]==table[i][i] and table[0][0] != 0:
            cont+=1
    if cont==3:
        return True, -1 if table[i][i] == -1 else 1
    
    cont=0
    #comprobar diagonal izquerda derecha
    for i in range(len(table)):
        if table[0][2]==table[i][len(table)-i-1] and table[0][2] != 0:
            cont+=1
    if cont==3:
        return True, -1 if table[i][0] == -1 else 1
    
    #si es estado final con empate o no es final
    for i in range(len(table)):
        for j in range(len(table)):
            if table[i][j]==0:
                return False,0
    return True, 2
pruebaes = Estado()
tablerop = [[0,  1, -1], [1, -1,  0], [-1,  0, 0]]
pruebaes.tablero=tablerop 
isendutil(pruebaes)

(True, -1)

In [5]:
def generarest(esta,juga):
    estados = []
    aux = deepcopy(esta.tablero)
    for i in range(len(aux)):
        for j in range(len(aux)):
            aux = deepcopy(esta.tablero)
            if aux[i][j]==0:
                aux[i][j]= 1 if juga==1 else -1
                temp = Estado()
                temp.tablero=deepcopy(aux)
                estados.append(temp)
                
    return estados

In [6]:
print(est)
det = generarest(est,1)


 │ │x
─┼─┼─
 │x│ 
─┼─┼─
 │ │ 




In [7]:
def fmin(estado):
    # si es estado final, retornar la utilidad para ese estado
    a,b = isendutil(estado)
    if a==True:
        return b

    valor = 10000
    # para cada estado siguiente:
    estads = generarest(estado,-1)
    for e in estads:
        valor = min(valor, fmax(e))
    return valor

In [8]:
def fmax(estado):
    # si es estado final, retornar la utilidad para ese estado
    a,b = isendutil(estado)
    if a==True:
        return b

    valor = -10000
    # para cada estado siguiente:
    estads = generarest(estado, 1)
    for e in estads:
        valor = max(valor, fmin(e))
    return valor

In [9]:
def decision_minimax(estado):
    mejor_jugada = None
    valor = -100000
    for e in generarest(estado,1):
        maximo = fmin(e)
        if  maximo > valor:
            valor = maximo
            mejor_jugada = e
    return mejor_jugada, valor

In [14]:
def decision_minimax_pc(estado):
    mejor_jugada = None
    valor = 100000
    for e in generarest(estado,1):
        maximo = fmin(e)
        if  maximo < valor:
            valor = maximo
            mejor_jugada = e
    return mejor_jugada, valor

In [10]:
actual = Estado(tablero = [[0,  0, 0], [0, 0,  0], [0,  0, 0]])
siguiente_movimiento, valor = decision_minimax(actual)
print(actual)
print("sig")
print(siguiente_movimiento)
print(valor)

 │ │ 
─┼─┼─
 │ │ 
─┼─┼─
 │ │ 


sig
x│ │ 
─┼─┼─
 │ │ 
─┼─┼─
 │ │ 


1


In [10]:
#modo juego 
#tablero seleccion
tab_juego = np.zeros([3,3],int)
cont = 1
for i in range(len(tab_juego)):
    for j in range(len(tab_juego)):
        tab_juego[i][j]=cont
        cont+=1
print(tab_juego)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
def juego(Estado, jugador):    
    if jugador==1:
        print("PLAYER")
        print(tab_juego)
        pos = input()
        resp = isempty(pos,esta.tablero,tab_juego)
        if resp == True:
            tablero=crate(pos,esta.tablero,tab_juego, jugador)
            esta.tablero=tablero
            return esta,int(2) 
    elif jugador==2:
        print("PC")
        nuevo,jugador = decision_minimax(esta)
        return nuevo,int(1)
    
def juego_pc(Estado, jugador):    
    if jugador==1:
        print("PC1")
        nuevo,jugador = decision_minimax_pc(esta)
        return nuevo,int(1)
    elif jugador==2:
        print("PC2")
        nuevo,jugador = decision_minimax(esta)
        return nuevo,int(1)

def isempty(op, tablero, tab_juego):
    for i in range(len(tab_juego)):
        for j in range(len(tablero)):
            if tab_juego[i][j] == int(op) and tablero[i][j]==0:
                return True
    return False

def crate(op, tablero, tab_juego,jugador):
    for i in range(len(tab_juego)):
        for j in range(len(tablero)):
            if tab_juego[i][j] == int(op) and tablero[i][j]==0:
                if jugador==1:
                    tablero[i][j]=-1
                else: 
                    tablero[i][j]=1
                return tablero
    return None
            

In [77]:
tablero = np.zeros([3,3],int)
esta = Estado(tablero=tablero)
final = False
jugador = rd.randint(1,2)
print(type(jugador))
print(jugador)
if (jugador == int(2)):
        esta.tablero[0][0]=1
        jugador=1
        print(esta)
        while not final:
            nuevo2, jugador2 = juego(esta,jugador)
            boo, valor = isendutil(nuevo2)
            final = boo
            jugador = jugador2
            esta = nuevo2
            print(esta)
            print(jugador)
else:
        while not final:
            nuevo2, jugador2 = juego(esta,jugador)
            boo, valor = isendutil(nuevo2)
            final = boo
            jugador = jugador2
            esta = nuevo2
            print(esta)
            print(jugador)


<class 'int'>
1
PLAYER
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
o│ │ 
─┼─┼─
 │ │ 
─┼─┼─
 │ │ 


2
PC
o│ │x
─┼─┼─
 │ │ 
─┼─┼─
 │ │ 


1
PLAYER
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
o│ │x
─┼─┼─
o│ │ 
─┼─┼─
 │ │ 


2
PC
o│ │x
─┼─┼─
o│ │ 
─┼─┼─
x│ │ 


1
PLAYER
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
o│ │x
─┼─┼─
o│o│ 
─┼─┼─
x│ │ 


2
PC
o│ │x
─┼─┼─
o│o│ 
─┼─┼─
x│ │x


1
PLAYER
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
o│ │x
─┼─┼─
o│o│o
─┼─┼─
x│ │x


2


In [111]:
rd.randint(1,2)

1

In [17]:
tablero_pc = np.zeros([3,3],int)
esta_pc = Estado(tablero=tablero_pc)
final_pc = False
jugador_pc = rd.randint(1,2)
while not final_pc:
    nuevo2_pc, jugador2_pc = juego_pc(esta_pc,jugador_pc)
    boo_pc, valor_pc = isendutil(nuevo2_pc)
    final_pc = boo_pc
    jugador_pc = jugador2_pc
    esta_pc = nuevo2_pc
    print(esta_pc)
    print(jugador_pc)

PC1


NameError: name 'esta' is not defined